import type { Metadata } from "next";
import "./globals.css";
import Sidebar from '@/components/sidebar/Sidebar'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          <Sidebar />
          <main className="flex-1 ml-0 overflow-y-auto h-screen flex flex-col items-center p-2 px-24">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
