import { PortfolioProject } from '@/types/portfolio';

export const portfolioProjects: PortfolioProject[] = [
  {
    id: 'project-1',
    title: 'HN Hiring Pro',
    description: 'Chrome Extension to help you manage your job applications on Who is Hiring Thread',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    imageUrl: '/images/projects/ecommerce.png',
    liveUrl: 'https://chromewebstore.google.com/detail/hn-hiring-pro/mpfaljjblphnlloddaplgicpkinikjlp',
    youtubeUrl: 'https://www.youtube.com/embed/nwz88GyAAXY',
    highlights: [
        'Implemented secure payment processing',
    ],
    date: '2024-01',
    status: 'Online',
  },
  {
    id: 'project-2',
    title: 'Lego',
    description: 'Lego is a platform for building and sharing your own Lego sets.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    imageUrl: 'https://i.ibb.co/w0hMGW7/image-10.png',
    liveUrl: 'https://lego.jaingautam.com/',
    highlights: [
        'Implemented secure payment processing',
    ],
    date: '2024-01',
    status: 'Online',
  },
  {
    id: 'project-3',
    title: 'LystOf',
    description: 'Create and share list of links.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    imageUrl: 'https://i.ibb.co/Js5WrBg/image-11.png',
    liveUrl: 'https://lego.jaingautam.com/',
    highlights: [
        'Implemented secure payment processing',
    ],
    date: '2024-01',
    status: 'Offline',
  },
  {
    id: 'project-4',
    title: 'Data Explorer',
    description: 'Data Explorer for viewing, filtering and analyzing datasets in browser.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    imageUrl: 'https://i.ibb.co/YyMyKRZ/explorer-preview.png',
    liveUrl: 'https://data.jaingautam.com/',
    highlights: [
        'Implemented secure payment processing',
    ],
    date: '2024-01',
    status: 'Online',
  },
  {
    id: 'project-5',
    title: 'Apply',
    description: 'Personalized Job Applications, Cover Letter and Resume. Learn How to Write a Cover Letter. Explore Tips for writing Powerful Cover Letter.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    imageUrl: 'https://i.ibb.co/wBcxbMJ/apply-preview.png',
    liveUrl: 'https://apply.jaingautam.com/',
    highlights: [
        'Implemented secure payment processing',
    ],
    date: '2024-01',
    status: 'Online',
  },
  {
    id: 'project-6',
    title: '💡 Wisdom Bar OS X',
    description: 'Get 200+ Wisdom Quotes on Entrepreneurship and Life, right in your Mac-Menu-Bar.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    imageUrl: 'https://i.ibb.co/2MYHWXG/wisdombar-preview.png',
    liveUrl: 'https://wisdombar.jaingautam.com/',
    highlights: [
        'Implemented secure payment processing',
    ],
    date: '2024-01',
    status: 'Online',
  },
  {
    id: 'project-7',
    title: 'Fantasy Golf Bag Dashboard',
    description: 'A data intensive dashboard.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    imageUrl: 'https://i.ibb.co/4RZfjcw/image-4.png',
    highlights: [
        'Implemented secure payment processing',
    ],
    date: '2024-01',
    status: 'Offline',
  },
  {
    id: 'project-8',
    title: 'Clap Or Slap',
    description: 'Clap or Slap to find products in a fun tinder-y way !',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    imageUrl: 'https://i.ibb.co/zH34qPH/image-10.png',
    highlights: [
      'Implemented secure payment processing',
    ],
    date: '2024-01',
    status: 'Offline',
  },
  {
    id: 'project-9',
    title: 'Makers Cafe',
    description: 'Discover Awesome Makers and what are they upto ?',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    imageUrl: 'https://i.ibb.co/fdGwKfS/image-5.png',
    highlights: [
      'Implemented secure payment processing',
    ],
    date: '2024-01',
    status: 'Offline',
  },
];