import { Project } from '@/types/project';

export const projects: Project[] = [
    {
        title: 'Use At',
        description: 'Use At to search with multiple AI and traditional search engines',
        technologies: ['WXT', 'React'],
        imageUrl: '/images/projects/ecommerce.png',
        liveUrl: 'https://chromewebstore.google.com/detail/use-at/dcccegjlioicfpgabhfpdjdddmjecdeg',
        videoUrl: "https://www.youtube.com/embed/w6qkxn5JSQI",
        date: '2025-02-26',
        status: 'Online',
    },
    {
        title: 'Prompt2MVP',
        description: 'Write quick prompts for your MVP on Lovable',
        technologies: ['WXT', 'React'],
        imageUrl: '/images/projects/ecommerce.png',
        liveUrl: 'https://chromewebstore.google.com/detail/prompt2mvp/dfojilkhdfjdlmhpchfajagmiamindgh?authuser=0&hl=en',
        videoUrl: "https://www.youtube.com/embed/WQIE-iw9aDc",
        date: '2025-01-27',
        status: 'Online',
    },    
    {
        title: 'LinkedIn AI Reply',
        description: 'Your AI LinkedIn Assistant',
        technologies: ['WXT', 'React'],
        imageUrl: '/images/projects/ecommerce.png',
        videoUrl: "https://youtube.com/embed/xuufGfeVGGM",
        githubUrl: 'https://github.com/gjain574/linkedin-ai-reply',
        date: '2024-01',
        status: 'Offline',
    },
    {
        title: 'HN Hiring Pro',
        description: 'Chrome Extension to help you manage your job applications on Who is Hiring Thread',
        technologies: ['WXT', 'React', 'Vanilla JS'],
        imageUrl: '/images/projects/ecommerce.png',
        liveUrl: 'https://chromewebstore.google.com/detail/hn-hiring-pro/mpfaljjblphnlloddaplgicpkinikjlp',
        videoUrl: 'https://www.youtube.com/embed/nwz88GyAAXY',
        date: '2024-01',
        status: 'Online',
    },
    {
        title: 'Next Pages',
        description: 'Next.js Pages for your blogs, projects, etc.',
        technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
        imageUrl: 'https://i.ibb.co/T0nLxjv/next-pages.png',
        liveUrl: 'https://jaingautam.com/',
        githubUrl: 'https://github.com/gjain574/next-pages',
        date: '2024-01',
        status: 'Online',
    },
    {
        title: 'Lego',
        description: 'Lego is a platform for building and sharing your own Lego sets.',
        technologies: ['React.js', 'React Table'],
        imageUrl: 'https://i.ibb.co/w0hMGW7/image-10.png',
        liveUrl: 'https://lego.jaingautam.com/',
        date: '2024-01',
        status: 'Online',
    },
    {
        title: 'LystOf',
        description: 'Create and share list of links.',
        technologies: ['React', 'Express', 'ElasticSearch'],
        imageUrl: 'https://i.ibb.co/Js5WrBg/image-11.png',
        liveUrl: 'https://lego.jaingautam.com/',
        date: '2024-01',
        status: 'Offline',
    },
    {
        title: 'Data Explorer',
        description: 'Data Explorer for viewing, filtering and analyzing datasets in browser.',
        technologies: ['React', 'React Table', 'React Select'],
        imageUrl: 'https://i.ibb.co/YyMyKRZ/explorer-preview.png',
        liveUrl: 'https://data.jaingautam.com/',
        date: '2024-01',
        status: 'Online',
    },
    {
        title: 'Apply',
        description: 'Personalized Job Applications, Cover Letter and Resume. Learn How to Write a Cover Letter. Explore Tips for writing Powerful Cover Letter.',
        technologies: ['HTML', 'Vanilla JS', 'Tailwind CSS'],
        imageUrl: 'https://i.ibb.co/wBcxbMJ/apply-preview.png',
        liveUrl: 'https://apply.jaingautam.com/',
        date: '2024-01',
        status: 'Online',
    },
    {
        title: '💡 Wisdom Bar OS X',
        description: 'Get 200+ Wisdom Quotes on Entrepreneurship and Life, right in your Mac-Menu-Bar.',
        technologies: ['Electron', 'React'],
        imageUrl: 'https://i.ibb.co/2MYHWXG/wisdombar-preview.png',
        liveUrl: 'https://wisdombar.jaingautam.com/',
        date: '2024-01',
        status: 'Online',
    },
    {
        title: 'Fantasy Golf Bag Dashboard',
        description: 'A data intensive dashboard.',
        technologies: ['React', 'React Table', 'Express'],
        imageUrl: 'https://i.ibb.co/4RZfjcw/image-4.png',
        date: '2024-01',
        status: 'Offline',
    },
    {
        title: 'Clap Or Slap',
        description: 'Clap or Slap to find products in a fun tinder-y way !',
        technologies: ['React', 'Express', 'ElasticSearch'],
        imageUrl: 'https://i.ibb.co/zH34qPH/image-10.png',
        date: '2024-01',
        status: 'Offline',
    },
    {
        title: 'Makers Cafe',
        description: 'Discover Awesome Makers and what are they upto ?',
        technologies: ['React', 'Express', 'ElasticSearch'],
        imageUrl: 'https://i.ibb.co/fdGwKfS/image-5.png',
        date: '2024-01',
        status: 'Offline',
    },
];